// @generated
// This file is @generated by prost-build.
/// Byte range in source text.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SourceSpan {
    #[prost(uint32, tag = "1")]
    pub start: u32,
    #[prost(uint32, tag = "2")]
    pub end: u32,
}
/// Location in a source file.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SourceLocation {
    #[prost(string, tag = "1")]
    pub file: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub span: ::core::option::Option<SourceSpan>,
    #[prost(uint32, tag = "3")]
    pub line: u32,
    #[prost(uint32, tag = "4")]
    pub column: u32,
}
include!("ogham.common.serde.rs");
// @@protoc_insertion_point(module)