// @generated
// This file is @generated by prost-build.
// ── Top-level IR container ─────────────────────────────────────────────

/// Fully resolved module — the output of the compiler's AST → IR lowering.
/// Everything is inline; plugins never need to resolve references.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Module {
    #[prost(string, tag = "1")]
    pub package: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub types: ::prost::alloc::vec::Vec<Type>,
    #[prost(message, repeated, tag = "3")]
    pub enums: ::prost::alloc::vec::Vec<Enum>,
    #[prost(message, repeated, tag = "4")]
    pub services: ::prost::alloc::vec::Vec<Service>,
}
// ── Type ───────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Type {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// package-qualified: "example.User"
    #[prost(string, tag = "2")]
    pub full_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub fields: ::prost::alloc::vec::Vec<Field>,
    #[prost(message, repeated, tag = "4")]
    pub oneofs: ::prost::alloc::vec::Vec<OneofGroup>,
    #[prost(message, repeated, tag = "5")]
    pub nested_types: ::prost::alloc::vec::Vec<Type>,
    #[prost(message, repeated, tag = "6")]
    pub nested_enums: ::prost::alloc::vec::Vec<Enum>,
    #[prost(message, repeated, tag = "7")]
    pub annotations: ::prost::alloc::vec::Vec<AnnotationCall>,
    /// types that reference this type
    #[prost(message, repeated, tag = "8")]
    pub back_references: ::prost::alloc::vec::Vec<TypeBackRef>,
    /// origin trace
    #[prost(message, optional, tag = "9")]
    pub trace: ::core::option::Option<TypeTrace>,
    #[prost(message, optional, tag = "10")]
    pub location: ::core::option::Option<super::common::SourceLocation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Field {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub number: u32,
    /// fully resolved, inline
    #[prost(message, optional, tag = "3")]
    pub r#type: ::core::option::Option<TypeReference>,
    #[prost(bool, tag = "4")]
    pub is_optional: bool,
    #[prost(bool, tag = "5")]
    pub is_repeated: bool,
    #[prost(message, repeated, tag = "6")]
    pub annotations: ::prost::alloc::vec::Vec<AnnotationCall>,
    /// projection source, if present
    #[prost(message, optional, tag = "7")]
    pub mapping: ::core::option::Option<FieldMapping>,
    /// origin trace (shape, etc.)
    #[prost(message, optional, tag = "8")]
    pub trace: ::core::option::Option<FieldTrace>,
    #[prost(message, optional, tag = "9")]
    pub location: ::core::option::Option<super::common::SourceLocation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OneofGroup {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub fields: ::prost::alloc::vec::Vec<OneofField>,
    #[prost(message, repeated, tag = "3")]
    pub annotations: ::prost::alloc::vec::Vec<AnnotationCall>,
    #[prost(message, optional, tag = "4")]
    pub location: ::core::option::Option<super::common::SourceLocation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OneofField {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub number: u32,
    #[prost(message, optional, tag = "3")]
    pub r#type: ::core::option::Option<TypeReference>,
    #[prost(message, repeated, tag = "4")]
    pub annotations: ::prost::alloc::vec::Vec<AnnotationCall>,
    #[prost(message, optional, tag = "5")]
    pub mapping: ::core::option::Option<FieldMapping>,
    #[prost(message, optional, tag = "6")]
    pub location: ::core::option::Option<super::common::SourceLocation>,
}
// ── Enum ───────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Enum {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub full_name: ::prost::alloc::string::String,
    /// includes implicit Unspecified=0
    #[prost(message, repeated, tag = "3")]
    pub values: ::prost::alloc::vec::Vec<EnumValue>,
    #[prost(message, repeated, tag = "4")]
    pub annotations: ::prost::alloc::vec::Vec<AnnotationCall>,
    #[prost(message, optional, tag = "5")]
    pub location: ::core::option::Option<super::common::SourceLocation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumValue {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub number: i32,
    #[prost(bool, tag = "3")]
    pub is_removed: bool,
    /// non-empty if is_removed
    #[prost(string, tag = "4")]
    pub fallback: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub annotations: ::prost::alloc::vec::Vec<AnnotationCall>,
    #[prost(message, optional, tag = "6")]
    pub location: ::core::option::Option<super::common::SourceLocation>,
}
// ── Service & RPC ──────────────────────────────────────────────────────

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Service {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub full_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub rpcs: ::prost::alloc::vec::Vec<Rpc>,
    #[prost(message, repeated, tag = "4")]
    pub annotations: ::prost::alloc::vec::Vec<AnnotationCall>,
    #[prost(message, optional, tag = "5")]
    pub location: ::core::option::Option<super::common::SourceLocation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Rpc {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub input: ::core::option::Option<RpcParam>,
    #[prost(message, optional, tag = "3")]
    pub output: ::core::option::Option<RpcParam>,
    #[prost(message, repeated, tag = "4")]
    pub annotations: ::prost::alloc::vec::Vec<AnnotationCall>,
    #[prost(message, optional, tag = "5")]
    pub location: ::core::option::Option<super::common::SourceLocation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RpcParam {
    #[prost(bool, tag = "1")]
    pub is_void: bool,
    #[prost(bool, tag = "2")]
    pub is_stream: bool,
    /// resolved inline (monomorphized if generic)
    #[prost(message, optional, tag = "3")]
    pub r#type: ::core::option::Option<TypeReference>,
}
// ── Type references (recursive, fully inline) ──────────────────────────

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypeReference {
    #[prost(oneof = "type_reference::Kind", tags = "1, 2, 3, 4")]
    pub kind: ::core::option::Option<type_reference::Kind>,
}
/// Nested message and enum types in `TypeReference`.
pub mod type_reference {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Scalar(super::ScalarType),
        /// resolved inline — fields, annotations, etc.
        #[prost(message, tag = "2")]
        MessageType(super::MessageType),
        /// resolved inline — all values
        #[prost(message, tag = "3")]
        EnumType(super::EnumType),
        #[prost(message, tag = "4")]
        Map(::prost::alloc::boxed::Box<super::MapType>),
    }
}
/// Primitive/scalar type.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScalarType {
    #[prost(enumeration = "ScalarKind", tag = "1")]
    pub scalar_kind: i32,
}
/// Reference to a message type — carries the full type inline.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageType {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub full_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub fields: ::prost::alloc::vec::Vec<Field>,
    #[prost(message, repeated, tag = "4")]
    pub oneofs: ::prost::alloc::vec::Vec<OneofGroup>,
    #[prost(message, repeated, tag = "5")]
    pub nested_enums: ::prost::alloc::vec::Vec<Enum>,
    #[prost(message, repeated, tag = "6")]
    pub annotations: ::prost::alloc::vec::Vec<AnnotationCall>,
}
/// Reference to an enum type — carries all values inline.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumType {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub full_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub values: ::prost::alloc::vec::Vec<EnumValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapType {
    #[prost(message, optional, boxed, tag = "1")]
    pub key: ::core::option::Option<::prost::alloc::boxed::Box<TypeReference>>,
    #[prost(message, optional, boxed, tag = "2")]
    pub value: ::core::option::Option<::prost::alloc::boxed::Box<TypeReference>>,
}
// ── Annotations (calls with full definitions inline) ───────────────────

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnnotationCall {
    /// "database", "validate", or "" for built-in
    #[prost(string, tag = "1")]
    pub library: ::prost::alloc::string::String,
    /// "Table", "Required", "default", etc.
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub arguments: ::prost::alloc::vec::Vec<AnnotationArgument>,
    /// full definition inline
    #[prost(message, optional, tag = "4")]
    pub definition: ::core::option::Option<AnnotationDefinition>,
    #[prost(message, optional, tag = "5")]
    pub location: ::core::option::Option<super::common::SourceLocation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnnotationArgument {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<AnnotationLiteral>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnnotationLiteral {
    #[prost(oneof = "annotation_literal::Value", tags = "1, 2, 3, 4, 5, 6")]
    pub value: ::core::option::Option<annotation_literal::Value>,
}
/// Nested message and enum types in `AnnotationLiteral`.
pub mod annotation_literal {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "1")]
        StringValue(::prost::alloc::string::String),
        #[prost(int64, tag = "2")]
        IntValue(i64),
        #[prost(double, tag = "3")]
        FloatValue(f64),
        #[prost(bool, tag = "4")]
        BoolValue(bool),
        #[prost(message, tag = "5")]
        StructValue(super::AnnotationStruct),
        #[prost(message, tag = "6")]
        ListValue(super::AnnotationList),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnnotationStruct {
    #[prost(map = "string, message", tag = "1")]
    pub fields: ::std::collections::HashMap<::prost::alloc::string::String, AnnotationLiteral>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnnotationList {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<AnnotationLiteral>,
}
/// Full annotation definition (schema).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnnotationDefinition {
    #[prost(string, tag = "1")]
    pub library: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// "type", "field", "enum", etc.
    #[prost(string, repeated, tag = "3")]
    pub targets: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "4")]
    pub parameters: ::prost::alloc::vec::Vec<AnnotationParameter>,
    /// included annotations
    #[prost(message, repeated, tag = "5")]
    pub compositions: ::prost::alloc::vec::Vec<AnnotationCompositionRef>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnnotationParameter {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub r#type: ::core::option::Option<TypeReference>,
    #[prost(bool, tag = "3")]
    pub is_optional: bool,
    /// present if has default
    #[prost(message, optional, tag = "4")]
    pub default_value: ::core::option::Option<AnnotationLiteral>,
}
/// Reference to a composed annotation.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnnotationCompositionRef {
    #[prost(string, tag = "1")]
    pub library: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub arguments: ::prost::alloc::vec::Vec<AnnotationArgument>,
}
// ── Projection mappings ────────────────────────────────────────────────

/// Source mapping for a projected field.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldMapping {
    /// Full chain from immediate source to root.
    /// Example: UserCard.name <- UserResponse.name <- User.first_name
    /// chain\[0\] = immediate source, chain\[last\] = root source.
    #[prost(message, repeated, tag = "1")]
    pub chain: ::prost::alloc::vec::Vec<MappingLink>,
}
/// One link in a projection chain.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MappingLink {
    /// "User"
    #[prost(string, tag = "1")]
    pub source_type_name: ::prost::alloc::string::String,
    /// "example.User"
    #[prost(string, tag = "2")]
    pub source_type_full_name: ::prost::alloc::string::String,
    /// "first_name"
    #[prost(string, tag = "3")]
    pub source_field_name: ::prost::alloc::string::String,
    /// for nested: \["billing", "street"\] or \["method", "*", "tx_id"\]
    #[prost(string, repeated, tag = "4")]
    pub path: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// inline
    #[prost(message, optional, tag = "5")]
    pub source_field_type: ::core::option::Option<TypeReference>,
    /// inline
    #[prost(message, repeated, tag = "6")]
    pub source_field_annotations: ::prost::alloc::vec::Vec<AnnotationCall>,
}
// ── Trace — origin metadata ────────────────────────────────────────────

/// Trace on a Type: where did this type come from?
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TypeTrace {
    #[prost(oneof = "type_trace::Origin", tags = "1, 2")]
    pub origin: ::core::option::Option<type_trace::Origin>,
}
/// Nested message and enum types in `TypeTrace`.
pub mod type_trace {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Origin {
        /// monomorphized from a generic
        #[prost(message, tag = "1")]
        Generic(super::GenericOrigin),
        /// created via Pick/Omit
        #[prost(message, tag = "2")]
        PickOmit(super::PickOmitOrigin),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GenericOrigin {
    /// "Paginated"
    #[prost(string, tag = "1")]
    pub source_name: ::prost::alloc::string::String,
    /// \["User"\]
    #[prost(string, repeated, tag = "2")]
    pub type_arguments: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PickOmitOrigin {
    /// "Pick" or "Omit"
    #[prost(string, tag = "1")]
    pub kind: ::prost::alloc::string::String,
    /// "User"
    #[prost(string, tag = "2")]
    pub source_type_name: ::prost::alloc::string::String,
    /// fields picked/omitted
    #[prost(string, repeated, tag = "3")]
    pub field_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Trace on a Field: where did this field come from?
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FieldTrace {
    /// non-null if field came from a shape injection
    #[prost(message, optional, tag = "1")]
    pub shape: ::core::option::Option<ShapeOrigin>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShapeOrigin {
    /// "Timestamps"
    #[prost(string, tag = "1")]
    pub shape_name: ::prost::alloc::string::String,
    /// "example.Timestamps"
    #[prost(string, tag = "2")]
    pub shape_full_name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub injection_range_start: u32,
    #[prost(uint32, tag = "4")]
    pub injection_range_end: u32,
    #[prost(message, optional, tag = "5")]
    pub shape_location: ::core::option::Option<super::common::SourceLocation>,
}
// ── Back-references ────────────────────────────────────────────────────

/// A reference from another type to this type.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TypeBackRef {
    #[prost(string, tag = "1")]
    pub referencing_type_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub referencing_type_full_name: ::prost::alloc::string::String,
    /// the field that holds the reference
    #[prost(string, tag = "3")]
    pub field_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ScalarKind {
    None = 0,
    Bool = 1,
    String = 2,
    Bytes = 3,
    Int8 = 4,
    Int16 = 5,
    Int32 = 6,
    Int64 = 7,
    Uint8 = 8,
    Uint16 = 9,
    Uint32 = 10,
    Uint64 = 11,
    Float = 12,
    Double = 13,
}
impl ScalarKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "SCALAR_KIND_NONE",
            Self::Bool => "BOOL",
            Self::String => "STRING",
            Self::Bytes => "BYTES",
            Self::Int8 => "INT8",
            Self::Int16 => "INT16",
            Self::Int32 => "INT32",
            Self::Int64 => "INT64",
            Self::Uint8 => "UINT8",
            Self::Uint16 => "UINT16",
            Self::Uint32 => "UINT32",
            Self::Uint64 => "UINT64",
            Self::Float => "FLOAT",
            Self::Double => "DOUBLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SCALAR_KIND_NONE" => Some(Self::None),
            "BOOL" => Some(Self::Bool),
            "STRING" => Some(Self::String),
            "BYTES" => Some(Self::Bytes),
            "INT8" => Some(Self::Int8),
            "INT16" => Some(Self::Int16),
            "INT32" => Some(Self::Int32),
            "INT64" => Some(Self::Int64),
            "UINT8" => Some(Self::Uint8),
            "UINT16" => Some(Self::Uint16),
            "UINT32" => Some(Self::Uint32),
            "UINT64" => Some(Self::Uint64),
            "FLOAT" => Some(Self::Float),
            "DOUBLE" => Some(Self::Double),
            _ => None,
        }
    }
}
include!("ogham.ir.serde.rs");
// @@protoc_insertion_point(module)