//! ogham-gen-proto — export .proto files from Ogham schemas.
//!
//! This is an Ogham plugin that receives the compiled IR and generates
//! standard .proto3 files compatible with protoc and buf.

use oghamgen::*;

fn main() {
    run(|req: CompileRequest| {
        let module = req.module.as_ref().ok_or("no module in request")?;
        let mut resp = CompileResponse::default();

        let package = &module.package;
        let mut w = CodeWriter::with_indent("  ");

        // Header
        w.raw("// Generated by ogham-gen-proto. DO NOT EDIT.");
        w.raw("syntax = \"proto3\";");
        w.newline();
        w.raw(&format!("package {};", proto_package(package)));
        w.newline();

        // Check if we need google.protobuf imports
        let needs_empty = module.services.iter().any(|s| {
            s.rpcs.iter().any(|r| {
                r.input.as_ref().is_some_and(|p| p.is_void)
                    || r.output.as_ref().is_some_and(|p| p.is_void)
            })
        });
        let has_annotations = has_any_annotations(module);

        if needs_empty {
            w.raw("import \"google/protobuf/empty.proto\";");
        }
        if has_annotations {
            w.raw("import \"google/protobuf/descriptor.proto\";");
            w.raw("import \"google/protobuf/struct.proto\";");
        }
        if needs_empty || has_annotations {
            w.newline();
        }

        // OghamAnnotation extension (if annotations present)
        if has_annotations {
            emit_ogham_options(&mut w);
            w.newline();
        }

        // Enums
        for en in &module.enums {
            emit_enum(&mut w, en);
            w.newline();
        }

        // Messages (types)
        for ty in &module.types {
            emit_message(&mut w, ty);
            w.newline();
        }

        // Services
        for svc in &module.services {
            emit_service(&mut w, svc);
            w.newline();
        }

        let filename = format!("{}.proto", package);
        resp.files.push(w.to_file(&filename));

        Ok(resp)
    });
}

// ── Proto package name ─────────────────────────────────────────────────

fn proto_package(ogham_package: &str) -> String {
    // Convert dots and slashes to dots for proto package
    ogham_package.replace('/', ".")
}

// ── Emit helpers ───────────────────────────────────────────────────────

fn emit_ogham_options(w: &mut CodeWriter) {
    w.raw("message OghamAnnotation {");
    w.raw("  string name = 1;");
    w.raw("  google.protobuf.Struct params = 2;");
    w.raw("}");
    w.newline();
    w.raw("extend google.protobuf.MessageOptions { repeated OghamAnnotation ogham_msg = 50000; }");
    w.raw("extend google.protobuf.FieldOptions { repeated OghamAnnotation ogham_field = 50001; }");
    w.raw("extend google.protobuf.OneofOptions { repeated OghamAnnotation ogham_oneof = 50002; }");
    w.raw("extend google.protobuf.EnumOptions { repeated OghamAnnotation ogham_enum = 50003; }");
    w.raw("extend google.protobuf.EnumValueOptions { repeated OghamAnnotation ogham_enum_value = 50004; }");
    w.raw("extend google.protobuf.ServiceOptions { repeated OghamAnnotation ogham_service = 50005; }");
    w.raw("extend google.protobuf.MethodOptions { repeated OghamAnnotation ogham_method = 50006; }");
}

fn emit_enum(w: &mut CodeWriter, en: &Enum) {
    emit_annotations_comment(w, &en.annotations);
    w.open(&format!("enum {} {{", en.name));
    for val in &en.values {
        let mut line = format!("{} = {};", val.name, val.number);
        if val.is_removed && !val.fallback.is_empty() {
            line = format!(
                "{} = {}; // @removed(fallback={})",
                val.name, val.number, val.fallback
            );
        }
        emit_annotations_comment(w, &val.annotations);
        w.line(&line);
    }
    w.close("}");
}

fn emit_message(w: &mut CodeWriter, ty: &Type) {
    emit_annotations_comment(w, &ty.annotations);
    w.open(&format!("message {} {{", ty.name));

    // Fields
    for field in &ty.fields {
        emit_field(w, field);
    }

    // Oneofs
    for oneof in &ty.oneofs {
        emit_annotations_comment(w, &oneof.annotations);
        w.open(&format!("oneof {} {{", oneof.name));
        for field in &oneof.fields {
            let proto_type = type_ref_to_proto(field.r#type.as_ref());
            emit_annotations_comment(w, &field.annotations);
            w.line(&format!("{} {} = {};", proto_type, field.name, field.number));
        }
        w.close("}");
    }

    // Nested enums
    for nested_enum in &ty.nested_enums {
        w.newline();
        emit_enum(w, nested_enum);
    }

    // Nested types
    for nested_type in &ty.nested_types {
        w.newline();
        emit_message(w, nested_type);
    }

    // Reserved fields
    // (not in IR currently, but future-proof)

    w.close("}");
}

fn emit_field(w: &mut CodeWriter, field: &Field) {
    let proto_type = type_ref_to_proto(field.r#type.as_ref());
    let mut prefix = String::new();

    if field.is_repeated {
        prefix = "repeated ".to_string();
    } else if field.is_optional {
        prefix = "optional ".to_string();
    }

    // Mapping comment
    let mapping_comment = if let Some(ref mapping) = field.mapping {
        if let Some(link) = mapping.chain.first() {
            let path: Vec<&str> = link.path.iter().map(|s| s.as_str()).collect();
            format!(" // <- {}", path.join("."))
        } else {
            String::new()
        }
    } else {
        String::new()
    };

    emit_annotations_comment(w, &field.annotations);
    w.line(&format!(
        "{}{} {} = {};{}",
        prefix, proto_type, field.name, field.number, mapping_comment
    ));
}

fn emit_service(w: &mut CodeWriter, svc: &Service) {
    emit_annotations_comment(w, &svc.annotations);
    w.open(&format!("service {} {{", svc.name));

    for rpc in &svc.rpcs {
        let input = rpc_param_to_proto(rpc.input.as_ref());
        let output = rpc_param_to_proto(rpc.output.as_ref());
        emit_annotations_comment(w, &rpc.annotations);
        w.line(&format!("rpc {}({}) returns ({}) {{}}", rpc.name, input, output));
    }

    w.close("}");
}

fn emit_annotations_comment(w: &mut CodeWriter, annotations: &[AnnotationCall]) {
    for ann in annotations {
        let name = if ann.library.is_empty() {
            ann.name.clone()
        } else {
            format!("{}::{}", ann.library, ann.name)
        };
        if ann.arguments.is_empty() {
            w.comment("//", &format!("@{}", name));
        } else {
            let args: Vec<String> = ann
                .arguments
                .iter()
                .map(|a| {
                    let val = a
                        .value
                        .as_ref()
                        .map(literal_to_string)
                        .unwrap_or_default();
                    if a.name.is_empty() {
                        val
                    } else {
                        format!("{}={}", a.name, val)
                    }
                })
                .collect();
            w.comment("//", &format!("@{}({})", name, args.join(", ")));
        }
    }
}

// ── Type conversion ────────────────────────────────────────────────────

fn type_ref_to_proto(tr: Option<&TypeReference>) -> String {
    let tr = match tr {
        Some(t) => t,
        None => return "bytes".to_string(),
    };

    match &tr.kind {
        Some(type_reference::Kind::Scalar(s)) => scalar_to_proto(s.scalar_kind),
        Some(type_reference::Kind::MessageType(m)) => m.name.clone(),
        Some(type_reference::Kind::EnumType(e)) => e.name.clone(),
        Some(type_reference::Kind::Map(m)) => {
            let key = type_ref_to_proto(m.key.as_deref());
            let val = type_ref_to_proto(m.value.as_deref());
            format!("map<{}, {}>", key, val)
        }
        None => "bytes".to_string(),
    }
}

fn scalar_to_proto(kind: i32) -> String {
    match ScalarKind::try_from(kind) {
        Ok(ScalarKind::Bool) => "bool",
        Ok(ScalarKind::String) => "string",
        Ok(ScalarKind::Bytes) => "bytes",
        Ok(ScalarKind::Int8) | Ok(ScalarKind::Int16) | Ok(ScalarKind::Int32) => "int32",
        Ok(ScalarKind::Int64) => "int64",
        Ok(ScalarKind::Uint8) | Ok(ScalarKind::Uint16) | Ok(ScalarKind::Uint32) => "uint32",
        Ok(ScalarKind::Uint64) => "uint64",
        Ok(ScalarKind::Float) => "float",
        Ok(ScalarKind::Double) => "double",
        _ => "bytes",
    }
    .to_string()
}

fn rpc_param_to_proto(param: Option<&RpcParam>) -> String {
    let param = match param {
        Some(p) => p,
        None => return "google.protobuf.Empty".to_string(),
    };

    if param.is_void {
        return "google.protobuf.Empty".to_string();
    }

    let mut s = String::new();
    if param.is_stream {
        s.push_str("stream ");
    }
    s.push_str(&type_ref_to_proto(param.r#type.as_ref()));
    s
}

fn literal_to_string(lit: &AnnotationLiteral) -> String {
    use annotation_literal::Value;
    match &lit.value {
        Some(Value::StringValue(s)) => format!("\"{}\"", s),
        Some(Value::IntValue(i)) => i.to_string(),
        Some(Value::FloatValue(f)) => f.to_string(),
        Some(Value::BoolValue(b)) => b.to_string(),
        _ => "...".to_string(),
    }
}

fn has_any_annotations(module: &Module) -> bool {
    module.types.iter().any(|t| {
        !t.annotations.is_empty()
            || t.fields.iter().any(|f| !f.annotations.is_empty())
            || t.oneofs.iter().any(|o| {
                !o.annotations.is_empty()
                    || o.fields.iter().any(|f| !f.annotations.is_empty())
            })
    }) || module
        .enums
        .iter()
        .any(|e| !e.annotations.is_empty() || e.values.iter().any(|v| !v.annotations.is_empty()))
        || module.services.iter().any(|s| {
            !s.annotations.is_empty() || s.rpcs.iter().any(|r| !r.annotations.is_empty())
        })
}
