// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Test {
    #[prost(string, tag = "1")]
    pub test_field: ::prost::alloc::string::String,
}
include!("ogham.serde.rs");
include!("ogham.tonic.rs");
// @@protoc_insertion_point(module)