// @generated
// This file is @generated by prost-build.
/// Sent to a plugin via stdin. Contains the fully resolved IR.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OghamCompileRequest {
    /// Compiler version that produced this request.
    #[prost(string, tag = "1")]
    pub compiler_version: ::prost::alloc::string::String,
    /// The module being compiled.
    #[prost(message, optional, tag = "2")]
    pub module: ::core::option::Option<super::ir::Module>,
    /// Plugin options from ogham.gen.yaml `opts` section.
    #[prost(map = "string, string", tag = "3")]
    pub options: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// Output directory specified in ogham.gen.yaml.
    #[prost(string, tag = "4")]
    pub output_dir: ::prost::alloc::string::String,
}
/// Returned by a plugin via stdout.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OghamCompileResponse {
    #[prost(message, repeated, tag = "1")]
    pub files: ::prost::alloc::vec::Vec<GeneratedFile>,
    #[prost(message, repeated, tag = "2")]
    pub errors: ::prost::alloc::vec::Vec<CompileError>,
}
/// A file produced by a plugin.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GeneratedFile {
    /// Path relative to output_dir.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// File contents.
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    /// If true, content is appended to existing file instead of overwriting.
    #[prost(bool, tag = "3")]
    pub append: bool,
}
/// An error reported by a plugin.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompileError {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(enumeration = "Severity", tag = "2")]
    pub severity: i32,
    /// Optional: source location that caused the error.
    #[prost(string, tag = "3")]
    pub source_type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub source_field: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Severity {
    None = 0,
    Error = 1,
    Warning = 2,
    Info = 3,
}
impl Severity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "SEVERITY_NONE",
            Self::Error => "ERROR",
            Self::Warning => "WARNING",
            Self::Info => "INFO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SEVERITY_NONE" => Some(Self::None),
            "ERROR" => Some(Self::Error),
            "WARNING" => Some(Self::Warning),
            "INFO" => Some(Self::Info),
            _ => None,
        }
    }
}
include!("ogham.compiler.serde.rs");
include!("ogham.compiler.tonic.rs");
// @@protoc_insertion_point(module)